name:
     
on:

jobs:
    build:
    

     - name: Start backend API
        working-directory: backend
        run: |
          npm run start:e2e &
          echo "Waiting for backend on http://localhost:3000/health ..."
          for i in {1..10}; do
            if curl -sSf http://localhost:3000/health > /dev/null; then
              echo "Backend is up !"
              exit 0
            fi
            echo "Still waiting..."
            sleep 2
          done
          echo "Backend did not start in time !"
          exit 1

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build:test
          start: npm run preview:test
          wait-on: "http://localhost:4173"
          browser: ${{ matrix.browser }}
          wait-on-timeout: 60
          config: baseUrl=http://localhost:4173